# Generated by Django 3.2 on 2021-09-29 20:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0002_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=cloudinary.models.CloudinaryField(default='.jpg,.png', max_length=255, verbose_name='image'),
        ),
    ]
